#ifndef PINS_H
#define PINS_H

#include "stm32f4xx_hal.h"

#define PIN_LED_POWER_GPIO_PORT    GPIOD
#define PIN_LED_POWER_PIN          GPIO_PIN_0
#define PIN_LED_ARMED_GPIO_PORT    GPIOD
#define PIN_LED_ARMED_PIN          GPIO_PIN_1
#define PIN_LED_MAINT_GPIO_PORT    GPIOD
#define PIN_LED_MAINT_PIN          GPIO_PIN_2
#define PIN_LED_ALARM_GPIO_PORT    GPIOD
#define PIN_LED_ALARM_PIN          GPIO_PIN_3
#define PIN_LED_RGB_R_PORT         GPIOD
#define PIN_LED_RGB_R_PIN          GPIO_PIN_12
#define PIN_LED_RGB_G_PORT         GPIOD
#define PIN_LED_RGB_G_PIN          GPIO_PIN_13
#define PIN_LED_RGB_B_PORT         GPIOD
#define PIN_LED_RGB_B_PIN          GPIO_PIN_14
#define PIN_RELAY_SIREN_INT_PORT   GPIOE
#define PIN_RELAY_SIREN_INT_PIN    GPIO_PIN_8
#define PIN_RELAY_SIREN_EXT_PORT   GPIOE
#define PIN_RELAY_SIREN_EXT_PIN    GPIO_PIN_9
#define PIN_RELAY_NEBBIOGENO_PORT  GPIOE
#define PIN_RELAY_NEBBIOGENO_PIN   GPIO_PIN_10
#define PIN_RELAY_OUT1_PORT        GPIOE
#define PIN_RELAY_OUT1_PIN         GPIO_PIN_11
#define PIN_RELAY_OUT2_PORT        GPIOE
#define PIN_RELAY_OUT2_PIN         GPIO_PIN_12
#define PIN_TAMPER_BUS_DIGITAL_PORT GPIOC
#define PIN_TAMPER_BUS_DIGITAL_PIN  GPIO_PIN_7
#define PIN_CAN_STB_PORT           GPIOA
#define PIN_CAN_STB_PIN            GPIO_PIN_8
#define PIN_BUTTON_RESET_PORT      GPIOC
#define PIN_BUTTON_RESET_PIN       GPIO_PIN_13

#endif
